language: node_js
node_js:
  - '8'
  - '6'
  - '4'
addons:
  chrome: stable # have Travis install chrome stable.
before_install:
  - "export CHROME_BIN=chromium-browser"
cache:
  directories:
    - node_modules
